theme: minima
title: The Max Janowski Society
description: >-
  Our mission is to increase audiences and enthusiasm for the music
  of Max Janowski (1912-1991); to collect, catalog, distribute,
  adapt, and publish new editions of his music; to educate performers,
  scholars, and the general public about his musical legacy; and
  to be the primary resource for information and discussion about
  Janowski’s scores, recordings and publications.
google_analytics: G-NWSXLYR4LN
include: [ '_pages' ]

header_pages:
  - _pages/1_about.md
  - _pages/2_music.md
  - _pages/3_donate.md
  - _pages/4_subscribe.md
